apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podcast-api
  description: Podcast API
  tags:
    - java
    - gamba
  links:
    - url: https://github.com/shukibakbuki/gamba
spec:
  type: experiment
  lifecycle: experimental
  owner: team-b
  system: podcast
